#!/bin/sh

# PROVIDE: promtail
# REQUIRE: LOGIN
# KEYWORD: shutdown

# Add the following line to /etc/rc.conf to enable promtail
# promtail_enable="YES"
#
# promtail_enable (bool):
#     Set it to YES to enable promtail
#     Set to NO by default
# promtail_user (string):
#     Set user that promtail will run under
#     Default is "loki"
# promtail_positions (string):
#     Set full path to positions file
#     Default is "/var/db/promtail/positions.yaml"
# promtail_config (string)
#     Set full path to config file
#     Default is "/usr/local/etc/promtail.yaml"
# promtail_args (string)
#     Set additional command line arguments
#     Default is ""

. /etc/rc.subr

name=promtail
rcvar=promtail_enable

load_rc_config $name

: ${promtail_enable:="no"}
: ${promtail_user:="loki"}
: ${promtail_group:="loki"}
: ${promtail_config:="/usr/local/etc/promtail.yaml"}
: ${promtail_positions:="/var/db/promtail/positions.yaml"}
: ${promtail_logfile:="/var/log/loki/promtail.log"}

pidfile="/var/run/${name}/${name}.pid"
required_files="${promtail_config}"

procname="/usr/local/bin/promtail"
command="/usr/sbin/daemon"

command_args="-p ${pidfile} -t ${name} -o ${promtail_logfile} \
	${procname} \
	-config.file=${promtail_config} \
	-positions.file=${promtail_positions} \
	-log.format=json \
	${promtail_args}"

start_precmd="promtail_start_precmd"

promtail_start_precmd()
{
	if [ ! -d "/var/run/${name}" ]; then
		install -d -m 0750 -o ${promtail_user} -g ${promtail_group} "/var/run/${name}"
	fi

        if [ ! -d "/var/log/loki" ]; then
		install -d -m 0750 -o ${promtail_user} -g ${promtail_group} "/var/log/loki/}"
	fi

	if [ ! -d "/var/db/promtail" ]; then
		install -d -m 0750 -o ${promtail_user} -g ${promtail_group} "/var/db/${name}"
	fi
}

run_rc_command "$1"