{% if helpers.exists('OmsVN.promtail.general') and OmsVN.promtail.general.enabled|default("0") == "1" %}
server:
  http_listen_port: {{ OmsVN.promtail.general.http_listen_port|default(9080) }}
  grpc_listen_port: {{ OmsVN.promtail.general.grpc_listen_port|default(0) }}

positions:
  filename: /var/tmp/promtail-syslog-positions.yml

clients:
  - url: {{ OmsVN.promtail.general.loki_url|default("http://127.0.0.1:3100/loki/api/v1/push") }}

{% if helpers.exists('OmsVN.promtail.general') and OmsVN.promtail.general.scrape_configs != "" %}
{{ OmsVN.promtail.general.scrape_configs }}
{% endif %}

{% endif %}